USE Technician
GO

DROP FUNCTION IF EXISTS GetOnHandPartsValueByCallNum
GO

CREATE FUNCTION GetOnHandPartsValueByCallNum(@CallNum INT)
RETURNS NUMERIC(10,2)
AS
BEGIN;
DECLARE @PartsValue NUMERIC(10,2)
SELECT  @PartsValue=SUM(DBO.PARTST.PRICE*DBO.PARTST.QTY_ON_HAND)
                 FROM DBO.SERVICE_PARTS_DETAIL JOIN DBO.PARTST
				 ON DBO.SERVICE_PARTS_DETAIL.PART_NUM=DBO.PARTST.PART_NUM
				 WHERE DBO.SERVICE_PARTS_DETAIL.CALL_NUM=@CallNum
				 GROUP BY DBO.SERVICE_PARTS_DETAIL.CALL_NUM
RETURN @PartsValue
END;

