DROP DATABASE IF EXISTS Technician
GO

CREATE DATABASE Technician
GO

USE Technician
GO

/*CREATE TABLE CUTOMERT*/

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('CUSTOMERT'))
BEGIN;
    DROP TABLE [CUSTOMERT];
END;
GO

CREATE TABLE [CUSTOMERT] (
    [CUST_NUM] INTEGER CONSTRAINT CUSTOMERT_PK PRIMARY KEY NOT NULL IDENTITY(1000, 1),
    [CUST_LAST] VARCHAR(50)NOT NULL,
    [CUST_FIRST] VARCHAR(50)NOT NULL,    
	[CUST_ADDRESS] VARCHAR(255) NULL,
    [CUST_CITY] VARCHAR(50) NULL,
    [CUST_STATE] VARCHAR(50) NULL,
);
GO

/*INSERT RECORDS TO TABLE CUTOMERT*/

INSERT INTO CUSTOMERT([CUST_LAST],[CUST_FIRST],[CUST_ADDRESS],[CUST_CITY],[CUST_STATE]) VALUES('Harper','Shaine','Ap #261-3932 Pellentesque Av.','Mogi das Cruzes','São Paulo');
INSERT INTO CUSTOMERT([CUST_LAST],[CUST_FIRST],[CUST_ADDRESS],[CUST_CITY],[CUST_STATE]) VALUES('Allen','Graham','Ap #851-2310 Urna Rd.','Yurimaguas','LOR');
INSERT INTO CUSTOMERT([CUST_LAST],[CUST_FIRST],[CUST_ADDRESS],[CUST_CITY],[CUST_STATE]) VALUES('Kiona','Jerry','5863 A Road','Apartadó','ANT');
INSERT INTO CUSTOMERT([CUST_LAST],[CUST_FIRST],[CUST_ADDRESS],[CUST_CITY],[CUST_STATE]) VALUES('Lana','Sean','198-260 Urna St.','Magangué','Bolívar');
INSERT INTO CUSTOMERT([CUST_LAST],[CUST_FIRST],[CUST_ADDRESS],[CUST_CITY],[CUST_STATE]) VALUES('Benjamin','Ethan','Ap #385-2419 Class Rd.','Lens-Saint-Remy','LU');


/*CREATE TABLE TECHNICIAN*/

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('TECHNICIAN'))
BEGIN;
    DROP TABLE [TECHNICIAN];
END;
GO

CREATE TABLE [TECHNICIAN] (
    [TECH_NUM] INTEGER CONSTRAINT TECHNICIAN_PK  PRIMARY KEY NOT NULL IDENTITY(10, 1),
    [TECH_LAST] VARCHAR(50) NOT NULL,
    [TECH_FIRST] VARCHAR(50) NOT NULL,    
	[HIRE_DATE] DATE NOT NULL,  
);
GO

/*INSERT RECORDS TO TABLE TECHNICIAN*/

INSERT INTO TECHNICIAN (TECH_LAST, TECH_FIRST, HIRE_DATE) VALUES ('Hutchinges', 'Anatollo', '2018/01/01');
INSERT INTO TECHNICIAN (TECH_LAST, TECH_FIRST, HIRE_DATE) VALUES ('Mansuer', 'Catlin', '2016/06/21');
INSERT INTO TECHNICIAN (TECH_LAST, TECH_FIRST, HIRE_DATE) VALUES('Yetton', 'Stu', '2010/12/11');
INSERT INTO TECHNICIAN (TECH_LAST, TECH_FIRST, HIRE_DATE) VALUES ('Berrie', 'Lynn', '2013/08/07');
INSERT INTO TECHNICIAN (TECH_LAST, TECH_FIRST, HIRE_DATE) VALUES ('Sayles', 'Elane', '2010/12/23');


/*CREATE TABLE PARTST*/

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('PARTST'))
BEGIN;
    DROP TABLE [PARTST];
END;
GO

CREATE TABLE [PARTST] (
    [PART_NUM] VARCHAR(50) CONSTRAINT PARTST_PK PRIMARY KEY  NOT NULL,
    [PART_DESC] VARCHAR(50) NOT NULL,
    [COST] NUMERIC(10,2) NOT NULL,    
	[PRICE] NUMERIC(10,2) NOT NULL,  
	[QTY_ON_HAND] INT NOT NULL,  

);
GO

/*INSERT RECORDS TO TABLE PARTST*/

INSERT INTO PARTST([PART_NUM],[PART_DESC],[COST],[PRICE],[QTY_ON_HAND]) VALUES('B0B-1D6','METER',18.27,69.11,652);
INSERT INTO PARTST([PART_NUM],[PART_DESC],[COST],[PRICE],[QTY_ON_HAND]) VALUES('L6D-3V7','DISC',33.38,84.81,202);
INSERT INTO PARTST([PART_NUM],[PART_DESC],[COST],[PRICE],[QTY_ON_HAND]) VALUES('L9A-9I7','CABLE',86.36,96.07,530);
INSERT INTO PARTST([PART_NUM],[PART_DESC],[COST],[PRICE],[QTY_ON_HAND]) VALUES('R2O-2R0','PIN',15.88,70.49,86);
INSERT INTO PARTST([PART_NUM],[PART_DESC],[COST],[PRICE],[QTY_ON_HAND]) VALUES('RRT-56E','JUMPER',5.12,13.39,112);

/*CREATE TABLE SERVICE_CALL*/

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('SERVICE_CALL'))
BEGIN;
    DROP TABLE [SERVICE_CALL];
END;
GO

CREATE TABLE [SERVICE_CALL] (
    [CALL_NUM] INT CONSTRAINT SERVER_CALL_PK PRIMARY KEY  IDENTITY (10000,1) NOT NULL,
    [CUST_NUM] INT CONSTRAINT SERVER_CALL_FK_CUSNUM FOREIGN KEY REFERENCES [CUSTOMERT](CUST_NUM) NOT NULL,
    [DATE] DATE NOT NULL,
    [TECH_NUM] INT CONSTRAINT SERVER_CALL_FK_TECHNUM FOREIGN KEY REFERENCES [TECHNICIAN](TECH_NUM) NOT NULL,

);
GO

/*INSERT RECORDS TO TABLE SERVICE_CALL*/

INSERT INTO SERVICE_CALL([CUST_NUM],[DATE],[TECH_NUM]) VALUES (1000,'2020/01/01',10);
INSERT INTO SERVICE_CALL([CUST_NUM],[DATE],[TECH_NUM]) VALUES (1000,'2020/05/01',12);
INSERT INTO SERVICE_CALL([CUST_NUM],[DATE],[TECH_NUM]) VALUES (1001,'2020/05/02',13);
INSERT INTO SERVICE_CALL([CUST_NUM],[DATE],[TECH_NUM]) VALUES (1001,'2020/06/03',14);
INSERT INTO SERVICE_CALL([CUST_NUM],[DATE],[TECH_NUM]) VALUES (1003,'2020/02/01',11);


/*CREATE TABLE SERVICE_PARTS_DETAIL*/

IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('SERVICE_PARTS_DETAIL'))
BEGIN;
    DROP TABLE [SERVICE_PARTS_DETAIL];
END;
GO

CREATE TABLE [SERVICE_PARTS_DETAIL] (
    [CALL_NUM] INT CONSTRAINT SERVICE_PARTS_DETAIL_FK_CALLNUM  FOREIGN KEY REFERENCES [SERVICE_CALL](CALL_NUM)  NOT NULL,
    [PART_NUM] VARCHAR(50) CONSTRAINT SERVICE_PARTS_DETAIL_FK_PARTNUM  FOREIGN KEY REFERENCES [PARTST](PART_NUM) NOT NULL,
    [QTY] INT NOT NULL,
	PRIMARY KEY ([CALL_NUM],[PART_NUM] )
);
GO

/*INSERT RECORDS TO TABLE SERVICE_PARTS_DETAIL*/
INSERT INTO SERVICE_PARTS_DETAIL([CALL_NUM],[PART_NUM],[QTY]) VALUES (10000,'B0B-1D6',2);
INSERT INTO SERVICE_PARTS_DETAIL([CALL_NUM],[PART_NUM],[QTY]) VALUES (10001,'L6D-3V7',3);
INSERT INTO SERVICE_PARTS_DETAIL([CALL_NUM],[PART_NUM],[QTY]) VALUES (10002,'L6D-3V7',2);
INSERT INTO SERVICE_PARTS_DETAIL([CALL_NUM],[PART_NUM],[QTY]) VALUES (10003,'L9A-9I7',1);
INSERT INTO SERVICE_PARTS_DETAIL([CALL_NUM],[PART_NUM],[QTY]) VALUES (10004,'R2O-2R0',10);


